inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - vendor/**/*
    - db/**/*
    - bin/**
    - node_modules/**/*
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
