version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo

    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose exec rails ./bin/setup
      - run: docker-compose exec rails ./bin/rubocop --parallel
      - run:
          name: Run spec
          command: |
            docker-compose exec rails ./bin/rspec \
                                      --format RspecJunitFormatter \
                                      --out /tmp/test-results/rspec.xml

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
