version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge

    working_directory: ~/repo

    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose run rails ./bin/setup
      - run: docker-compose run rails ./bin/rubocop --parallel
      - run:
          name: Run spec
          command: |
            docker-compose run rails ./bin/rspec \
                                     --format RspecJunitFormatter \
                                     --out /tmp/test-results/rspec.xml

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
