default: &default
  adapter:  mysql2
  encoding: utf8
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host:     <%= Settings.mysql.host %>
  username: <%= Settings.mysql.username %>
  password: <%= Settings.mysql.password %>

development:
  <<: *default
  database: bot-farm_development

test:
  <<: *default
  database: bot-farm_test

production:
  <<: *default
  database: bot-farm_production
