AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless application to handle event hooks from Slack

Resources:
  BotFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Events:
        Api:
          Type: Api
          Properties:
            Path: /events
            Method: post
